# Generated by Django 5.1.4 on 2025-01-03 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Ação', 'Ação'), ('Aventura', 'Aventura'), ('Animação', 'Animação'), ('Comédia', 'Comédia'), ('Crime', 'Crime'), ('Documentário', 'Documentário'), ('Drama', 'Drama'), ('Família', 'Família'), ('Fantasia', 'Fantasia'), ('Ficção Científica', 'Ficção Científica'), ('Guerra', 'Guerra'), ('História', 'História'), ('Mistério', 'Mistério'), ('Musical', 'Musical'), ('Romance', 'Romance'), ('Suspense', 'Suspense'), ('Terror', 'Terror'), ('Western', 'Western')], max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=244, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=244)),
                ('url', models.CharField(max_length=244, null=True)),
                ('sinopse', models.CharField(max_length=488, null=True)),
                ('img', models.FileField(upload_to='movieImgs/')),
                ('watched', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='movie_category', to='filmes.category')),
                ('fk_saga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saga_movie', to='filmes.saga')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Pedro Lucas', 'Pedro Lucas'), ('Sarah', 'Sarah')], max_length=244)),
                ('text', models.CharField(max_length=244)),
                ('dt_comment', models.DateTimeField(auto_now_add=True)),
                ('fk_movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_comment', to='filmes.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Pedro Lucas', 'Pedro Lucas'), ('Sarah', 'Sarah')], max_length=244)),
                ('rate', models.FloatField(choices=[(0.0, 0.0), (0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], default=0)),
                ('fk_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_rate', to='filmes.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_session', models.DateTimeField(auto_now_add=True)),
                ('fk_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_session', to='filmes.movie')),
            ],
        ),
    ]
