# Generated by Django 5.1.4 on 2025-01-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_remove_comment_name_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='fk_user',
        ),
        migrations.AddField(
            model_name='review',
            name='dt_review',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt_comment',
            field=models.DateTimeField(null=True),
        ),
    ]
