# Generated by Django 5.1.4 on 2025-01-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_rename_user_comment_fk_user_review_dt_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=488),
        ),
    ]
