# Generated by Django 5.1.4 on 2025-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0006_alter_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(error_messages={'unique': 'Filme com este Nome já existe.'}, max_length=244, unique=True),
        ),
    ]
